package com.example.model

data class Article(
    val uid: Int,
    val apkLink: String,
    val audit: Int,
    val author: String,
    val canEdit: Boolean,
    val chapterId: Int,
    val chapterName: String,
    var collect: Boolean,
    val courseId: Int,
    var desc: String,
    val descMd: String,
    val envelopePic: String,
    val fresh: Boolean,
    val id: Int,
    val link: String,
    val niceDate: String,
    val niceShareDate: String,
    val origin: String,
    val prefix: String,
    val projectLink: String,
    val publishTime: Long,
    val selfVisible: Int,
    val shareDate: Long,
    val shareUser: String,
    val superChapterId: Int,
    val superChapterName: String,
    val title: String,
    val type: Int,
    val userId: Int,
    val visible: Int,
    val zan: Int,
    var localType: Int
)
/**
 * "adminAdd": false,
 * "apkLink": "",
 * "audit": 1,
 * "author": "",
 * "canEdit": false,
 * "chapterId": 494,
 * "chapterName": "广场",
 * "collect": false,
 * "courseId": 13,
 * "desc": "",
 * "descMd": "",
 * "envelopePic": "",
 * "fresh": false,
 * "host": "",
 * "id": 31041,
 * "isAdminAdd": false,
 * "link": "https:\/\/juejin.cn\/post\/7587256133791957032",
 * "niceDate": "2026-01-03 19:08",
 * "niceShareDate": "2026-01-03 18:58",
 * "origin": "",
 * "prefix": "",
 * "projectLink": "",
 * "publishTime": 1767438519000,
 * "realSuperChapterId": 493,
 * "selfVisible": 0,
 * "shareDate": 1767437925000,
 * "shareUser": "鸿洋",
 * "superChapterId": 494,
 * "superChapterName": "广场Tab",
 * "tags": [],
 * "title": "面试官更爱问的 Android 数据传递问题如何处理 Deep link ？",
 * "type": 0,
 * "userId": 2,
 * "visible": 1,
 * "zan": 0
 */